spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: 6f9d2a39-de64-4604-bf98-617c17677168
        app-id-uri: api://6f9d2a39-de64-4604-bf98-617c17677168
